import os
os.chdir('/home/ubuntu/leadscrape')
os.system("git reset --hard")
os.system("git pull")
os.system('sudo chown :www-data ~/leadscrape/')
os.system('sudo chmod 777 -R ~/leadscrape/')
os.system('mkdir -p /home/ubuntu/leadscrape/media/downloads')
os.system('sudo chown -R www-data:www-data /home/ubuntu/leadscrape/media/')
os.system('sudo chmod -R 775 /home/ubuntu/leadscrape/media/')
os.system('sudo systemctl restart apache2')
os.system ('cat /etc/apache2/envvars')
