import os
os.chdir('/home/ubuntu/contact_search')
os.system("git reset --hard")
os.system("git pull")
os.system('sudo chown :www-data ~/contact_search/')
os.system('sudo chmod 777 -R ~/contact_search/')
os.system('mkdir -p /home/ubuntu/contact_search/media/downloads')
os.system('sudo chown -R www-data:www-data /home/ubuntu/contact_search/media/')
os.system('sudo chmod -R 775 /home/ubuntu/contact_search/media/')
os.system('sudo systemctl restart apache2')
os.system ('cat /etc/apache2/envvars')
